env:
  global:
    - PYFUNCEBLE_AUTO_CONFIGURATION="PyFunceble"
    - GIT_EMAIL: dead_hosts@funilrys.com
    - GIT_NAME: Travis CI
    - secure: ybs5NmE5QFyebfMAvBLY5LXVTnKuInHcG7vLW7KF9fKLz2QSLsiy4Nc/8Dju+xfR1uC5VsnxSnWPa9JAlaCBxccFPb4OPKNWclTIOMedyRRPu2hSqqQLxqepqQxHA2h8Dd4f3QgwvO1SMPOk6w/e+OlAx2UnKw9aJwqD1bIg0a1ixfCu30jkuhmAe5YZbLky6UyCgX3yMHdt9BQC+QyY7VYcJQlvdXky5SnvQ/knXRfID0/Aj1/YvzRpyqfVO553GD2YxwL4jkTQrJrgxTAW59HhRGC1hMrJS/G7P/uVr53blVFJClYCq4FO9f8XGGYZOLYMWuTsYTDjEd71zY/Xv5cbCQmm7+2eWkjKy9K2lIHtn8x+/uXh0oy7oluBqv+Vs5qO28oOoEpxqNl0NuwHjicSROWe7mXBJ86zICkrl/1ukyPrb8URY5sEQqJCTVF+cgUFgfPOrdH80Gem9DV84UrUKWcVu6u3qfmouqNZE79hcOnIKxfxIYS/cVkKNvJ54SbEa8r0OerEWv0nCeVcLOsZgJrFI5gpG3rwPMRKDjj4cfGuQ8tZ4cbB3TOBWbLdI+/fVnEgiQdFQ2V+y+IBZj+rs6qwjslpBg5ojOMXC4qV5OMEc5/HSe1vrt0JHnbGHoYWlLdFpQxxBISMe/GoaUWWYSQthfS8QOuDPQrx0wQ=
    
install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda env create -q -f ${TRAVIS_BUILD_DIR}/.environment.yaml
  - source activate iana
  - python --version --version
  - pip --version
  - conda --version

dist: bionic
os: linux
language: generic
script:
  - ./update.py

notifications:
  on_success: change
  on_failure: always
